dist: xenial

language: node_js
node_js: '10'

install:
  - npm ci

script:
  - npm run build
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rpc .
  - docker images
  - docker tag rpc $DOCKER_USERNAME/rpc:latest
  - docker push $DOCKER_USERNAME/rpc:latest
